### ISSUE TITLE
chore: few improv

### ISSUE THREAD

**Issue by vmarchaud** [reelevant-tech/analytics-ios#1]
- [x] Dont retry events that are more than 15min old (https://github.com/reelevant-tech/analytics-ios/blob/main/Sources/ReelevantAnalytics/ReelevantAnalytics.swift#L146)
- [x] We send `product_page` event name for both brand_view, category_view and product_hover, purchase, add_cart: https://github.com/reelevant-tech/analytics-ios/blob/main/Sources/ReelevantAnalytics/ReelevantAnalytics.swift#L187, https://github.com/reelevant-tech/analytics-ios/blob/main/Sources/ReelevantAnalytics/ReelevantAnalytics.swift#L177,
https://github.com/reelevant-tech/analytics-ios/blob/main/Sources/ReelevantAnalytics/ReelevantAnalytics.swift#L169
- [x] Only publish identify if the value wasn't stored previously (https://github.com/reelevant-tech/analytics-ios/blob/main/Sources/ReelevantAnalytics/ReelevantAnalytics.swift#L199)
- [x] Could we set a user agent with the correct ios version ? https://github.com/reelevant-tech/analytics-ios/blob/main/Sources/ReelevantAnalytics/ReelevantAnalytics.swift#L257
- [x] increase timeout to 60s

Question:
 - Are we sending the userId in the identify ? https://github.com/reelevant-tech/analytics-ios/blob/main/Sources/ReelevantAnalytics/ReelevantAnalytics.swift#L199

**Comment by vmarchaud** [comment]
I think we should also increase the retry queue to 1min to avoid spamming our backend WDYT ?

**Comment by Eywek** [comment]
> * Are we sending the userId in the identify ?

Yep it's sent in the `clientId` property

https://github.com/reelevant-tech/analytics-ios/blob/4763d5a988adce591b29e3de890ba61d9bd13bbf/Sources/ReelevantAnalytics/ReelevantAnalytics.swift?rgh-link-date=2022-10-06T12%3A40%3A36Z#L199
https://github.com/reelevant-tech/analytics-ios/blob/4763d5a988adce591b29e3de890ba61d9bd13bbf/Sources/ReelevantAnalytics/ReelevantAnalytics.swift?rgh-link-date=2022-10-06T12%3A40%3A36Z#L240
https://github.com/reelevant-tech/analytics-ios/blob/4763d5a988adce591b29e3de890ba61d9bd13bbf/Sources/ReelevantAnalytics/ReelevantAnalytics.swift?rgh-link-date=2022-10-06T12%3A40%3A36Z#L286

> I think we should also increase the retry queue to 1min to avoid spamming our backend WDYT ?

We could, I've used the web one https://github.com/reelevant-tech/analytics-web/blob/a4f1a316a1f14487884b5d91baefc57a316ceeea/client/src/lib/tracker.ts#L276
